version: "3"

services:
  sonarqube:
    image: sonarqube
    networks:
      - proxy
      - sonar_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.sonar.entrypoints=http"
      - "traefik.http.routers.sonar.rule=Host(`${SONAR_DOMAIN}`)"
      - "traefik.http.routers.sonar.middlewares=traefik-https-redirect"
      - "traefik.http.routers.sonar-secure.entrypoints=https"
      - "traefik.http.routers.sonar-secure.rule=Host(`${SONAR_DOMAIN}`)"
      - "traefik.http.routers.sonar-secure.tls.certresolver=http"
      - "traefik.http.services.sonar.loadbalancer.server.port=9000"
 
networks:
  sonar_network:
    driver: bridge
    internal: true
  proxy:
    external:
      name: traefik_proxy
